image: "flowdalic/debian-dev:1.4"

before_script:
  - apt update -qq
  - >
    apt install -y --no-install-recommends
    git
    cmake
    pipenv
  - pipenv install --dev

allocbench:
  script:
    pipenv run make check
